export interface PuzzleSeed {
  question: string;
  answerA: string;
  answerB: string;
  correct: "A" | "B";
  difficulty: "EASY" | "MEDIUM" | "HARD" | "SPECIAL";
  category: string;
  explanation?: string;
  hint?: string;
}

export const puzzleSeeds: PuzzleSeed[] = [
  {
    question: "What number comes next?\n2 → 4\n3 → 9\n4 → ?",
    answerA: "12",
    answerB: "16",
    correct: "B",
    difficulty: "EASY",
    category: "Pattern",
    explanation: "Each number is squared: 4^2 = 16.",
    hint: "Try squaring the input.",
  },
  {
    question: "Which word does not belong?\nApple, Banana, Carrot, Cherry",
    answerA: "Carrot",
    answerB: "Cherry",
    correct: "A",
    difficulty: "EASY",
    category: "Logic",
    explanation: "Carrot is a vegetable; the rest are fruits.",
  },
  {
    question: "If all Zips are Zaps, and all Zaps are Zops, are all Zips definitely Zops?",
    answerA: "Yes",
    answerB: "No",
    correct: "A",
    difficulty: "EASY",
    category: "Deduction",
    explanation: "Transitive property of the given statements.",
  },
  {
    question: "A clock shows 3:15. What is the angle between the hour and minute hands (nearest option)?",
    answerA: "7.5°",
    answerB: "90°",
    correct: "A",
    difficulty: "MEDIUM",
    category: "Mathematical reasoning",
    explanation: "At 3:15 the hour hand has moved slightly past 3, giving a 7.5° gap.",
  },
  {
    question: "Decode the Caesar cipher (shift 1): 'IPMMP'",
    answerA: "HELLO",
    answerB: "WORLD",
    correct: "A",
    difficulty: "MEDIUM",
    category: "Cipher",
    hint: "Shift each letter back by one.",
  },
  {
    question: "Five friends sit in a row. Ana is left of Ben. Cara is right of Ben. Who is in the middle if only these three are considered?",
    answerA: "Ben",
    answerB: "Ana",
    correct: "A",
    difficulty: "MEDIUM",
    category: "Deduction",
  },
  {
    question: "A farmer has 17 sheep, all but 9 die. How many are left?",
    answerA: "8",
    answerB: "9",
    correct: "B",
    difficulty: "MEDIUM",
    category: "Observation",
    explanation: "\"All but 9 die\" means 9 survive.",
  },
  {
    question: "What is the next number?\n1, 1, 2, 3, 5, 8, ?",
    answerA: "11",
    answerB: "13",
    correct: "B",
    difficulty: "MEDIUM",
    category: "Pattern",
    explanation: "Fibonacci sequence: 5 + 8 = 13.",
  },
  {
    question: "A detective finds a suspect claims to have been asleep during a storm, but the town had no storm and no power outage that night. What gives the suspect away?",
    answerA: "There was no storm to sleep through",
    answerB: "The suspect has an alibi witness",
    correct: "A",
    difficulty: "HARD",
    category: "Mystery",
  },
  {
    question: "Solve: If 5 machines make 5 widgets in 5 minutes, how long do 100 machines take to make 100 widgets?",
    answerA: "100 minutes",
    answerB: "5 minutes",
    correct: "B",
    difficulty: "HARD",
    category: "Logic",
    explanation: "Each machine makes 1 widget in 5 minutes regardless of count.",
  },
  {
    question: "Which cipher word decrypts (Atbash) to 'ZOO'?\n(Atbash: A<->Z, B<->Y ...)",
    answerA: "ALL",
    answerB: "SUN",
    correct: "A",
    difficulty: "HARD",
    category: "Cipher",
    hint: "Atbash reflects each letter across the alphabet.",
  },
  {
    question: "A bat and a ball cost $1.10 total. The bat costs $1.00 more than the ball. How much is the ball?",
    answerA: "$0.10",
    answerB: "$0.05",
    correct: "B",
    difficulty: "SPECIAL",
    category: "Mathematical reasoning",
    explanation: "Ball = x, bat = x+1, 2x+1=1.10 => x=0.05.",
  },
  {
    question: "In a room of 23 people, is it more likely than not that two share a birthday?",
    answerA: "Yes",
    answerB: "No",
    correct: "A",
    difficulty: "SPECIAL",
    category: "Mathematical reasoning",
    explanation: "The classic birthday paradox crosses 50% at 23 people.",
  },
  {
    question: "What comes next in the word pattern?\nCAT, DOG, ?, EAGLE (by letter count 3,3,4,5)",
    answerA: "LION",
    answerB: "BEAR",
    correct: "A",
    difficulty: "SPECIAL",
    category: "Word",
    explanation: "LION has 4 letters, matching the increasing count pattern.",
  },
  {
    question: "Observation: A wall clock's reflection in a mirror shows 9:20. What is the real time?",
    answerA: "2:40",
    answerB: "3:40",
    correct: "A",
    difficulty: "SPECIAL",
    category: "Observation",
    explanation: "Mirror time = 12:00 minus shown time = 2:40.",
  },

  // ---- Logic ----
  { question: "If it is true that 'All cats are animals' and 'Whiskers is a cat', is Whiskers an animal?", answerA: "Yes", answerB: "No", correct: "A", difficulty: "EASY", category: "Logic", explanation: "Direct syllogism." },
  { question: "Either the light is on or off. It is not on. What is it?", answerA: "Off", answerB: "Unknown", correct: "A", difficulty: "EASY", category: "Logic", explanation: "Exclusive either/or with one ruled out." },
  { question: "If no fish can fly, and a salmon is a fish, can a salmon fly?", answerA: "No", answerB: "Yes", correct: "A", difficulty: "EASY", category: "Logic" },
  { question: "A statement says 'This sign has exactly one false word.' If the sign has exactly one false word, is the statement itself true?", answerA: "Yes", answerB: "No", correct: "A", difficulty: "HARD", category: "Logic", explanation: "Self-referential but consistent if exactly one word (arguably 'one') is false." },
  { question: "Three boxes: one has only apples, one only oranges, one both — but all labels are wrong. You draw one fruit from the box labeled 'Apples & Oranges'. It's an apple. What is that box?", answerA: "Apples only", answerB: "Oranges only", correct: "A", difficulty: "HARD", category: "Logic", explanation: "Since all labels are wrong, the mixed label can't be mixed, and drawing an apple confirms apples-only." },
  { question: "If some Bloops are Razzies and all Razzies are Lazzies, must some Bloops be Lazzies?", answerA: "Yes", answerB: "No", correct: "A", difficulty: "MEDIUM", category: "Logic" },
  { question: "A implies B. B is false. What can we say about A?", answerA: "A is false", answerB: "A is true", correct: "A", difficulty: "MEDIUM", category: "Logic", explanation: "Modus tollens." },
  { question: "Two guards: one always lies, one always tells the truth. You ask a guard 'Does the other guard lie?' and they answer 'Yes'. Both guards would answer 'Yes' to this exact question. Can this question alone identify who lies?", answerA: "No", answerB: "Yes", correct: "A", difficulty: "HARD", category: "Logic", explanation: "The truth-teller truthfully says the liar lies ('Yes'); the liar falsely denies the truth-teller lies, which is also 'Yes'. Both answer identically, so the question is uninformative." },
  { question: "If today is not Monday, and tomorrow is not Wednesday, could today be Tuesday?", answerA: "Yes", answerB: "No", correct: "A", difficulty: "EASY", category: "Logic" },
  { question: "All squares are rectangles. Some rectangles are not squares. Is every rectangle a square?", answerA: "No", answerB: "Yes", correct: "A", difficulty: "EASY", category: "Logic" },
  { question: "If P then Q. Q is true. Can we conclude P is true?", answerA: "No", answerB: "Yes", correct: "A", difficulty: "MEDIUM", category: "Logic", explanation: "Affirming the consequent is a logical fallacy." },
  { question: "A box contains only red and blue balls. You're told it's NOT the case that there are no red balls. Are there red balls?", answerA: "Yes", answerB: "No", correct: "A", difficulty: "MEDIUM", category: "Logic", explanation: "Double negative resolves to a positive." },
  { question: "Of five statements, exactly one is true: 'I am 1st', 'I am 2nd', 'I am 3rd', 'I am 4th', 'I am 5th' (each spoken by a different person about their own rank, all distinct). Which rank must be true for consistency to allow exactly one truth?", answerA: "It depends on positions, but exactly one can be consistent", answerB: "None can ever be true", correct: "A", difficulty: "HARD", category: "Logic" },

  // ---- Pattern ----
  { question: "What comes next?\n1, 4, 9, 16, ?", answerA: "20", answerB: "25", correct: "B", difficulty: "EASY", category: "Pattern", explanation: "Perfect squares: 5^2 = 25." },
  { question: "What comes next?\n3, 6, 9, 12, ?", answerA: "14", answerB: "15", correct: "B", difficulty: "EASY", category: "Pattern", explanation: "Add 3 each time." },
  { question: "What comes next?\n2, 4, 8, 16, ?", answerA: "24", answerB: "32", correct: "B", difficulty: "EASY", category: "Pattern", explanation: "Doubling each step." },
  { question: "What comes next?\nA, C, E, G, ?", answerA: "H", answerB: "I", correct: "B", difficulty: "EASY", category: "Pattern", explanation: "Skip one letter each time." },
  { question: "What comes next?\n100, 90, 81, 73, ?", answerA: "66", answerB: "64", correct: "A", difficulty: "MEDIUM", category: "Pattern", explanation: "Differences decrease by 1 each time: -10,-9,-8,-7." },
  { question: "What comes next?\n1, 2, 4, 7, 11, ?", answerA: "15", answerB: "16", correct: "B", difficulty: "MEDIUM", category: "Pattern", explanation: "Differences increase by 1: +1,+2,+3,+4,+5." },
  { question: "What comes next?\n2, 6, 12, 20, 30, ?", answerA: "40", answerB: "42", correct: "B", difficulty: "MEDIUM", category: "Pattern", explanation: "Differences of consecutive even numbers: n(n+1)." },
  { question: "What comes next?\n1, 1, 2, 6, 24, ?", answerA: "96", answerB: "120", correct: "B", difficulty: "HARD", category: "Pattern", explanation: "Factorials: 5! = 120." },
  { question: "What comes next?\n3, 9, 27, 81, ?", answerA: "162", answerB: "243", correct: "B", difficulty: "EASY", category: "Pattern", explanation: "Powers of 3." },
  { question: "What comes next?\nZ, X, V, T, ?", answerA: "S", answerB: "R", correct: "B", difficulty: "MEDIUM", category: "Pattern", explanation: "Every other letter backward." },
  { question: "What comes next?\n1, 8, 27, 64, ?", answerA: "100", answerB: "125", correct: "B", difficulty: "HARD", category: "Pattern", explanation: "Perfect cubes: 5^3 = 125." },
  { question: "What comes next?\n5, 10, 20, 40, ?", answerA: "60", answerB: "80", correct: "B", difficulty: "EASY", category: "Pattern", explanation: "Doubling." },

  // ---- Observation ----
  { question: "Which of these is heavier: a kilogram of feathers or a kilogram of steel?", answerA: "They weigh the same", answerB: "Steel is heavier", correct: "A", difficulty: "EASY", category: "Observation" },
  { question: "A man looks at a portrait and says 'I have no siblings, but that man's father is my father's son.' Whose portrait is he looking at?", answerA: "His son", answerB: "Himself", correct: "A", difficulty: "HARD", category: "Observation", explanation: "'My father's son' with no siblings is himself, so the portrait's father is the speaker — meaning the portrait is his son." },
  { question: "You see a boat with a ladder; 3 rungs are underwater, rungs are 20cm apart, and the tide rises 20cm/hour. After 2 hours, how many rungs are underwater?", answerA: "3", answerB: "7", correct: "A", difficulty: "HARD", category: "Observation", explanation: "The boat floats, so it rises with the tide — the number of submerged rungs never changes." },
  { question: "How many months have 28 days?", answerA: "1", answerB: "12", correct: "B", difficulty: "EASY", category: "Observation", explanation: "Every month has at least 28 days." },
  { question: "A rooster lays an egg on the exact peak of a barn roof. Which side does it roll down?", answerA: "Neither — roosters don't lay eggs", answerB: "The steeper side", correct: "A", difficulty: "EASY", category: "Observation" },
  { question: "You walk into a room with a match, a candle, and a fireplace, all unlit. Which do you light first?", answerA: "The match", answerB: "The candle", correct: "A", difficulty: "EASY", category: "Observation" },
  { question: "A digital clock shows 12:34. Looking at your watch in a mirror, what looks different?", answerA: "The digits appear reversed", answerB: "Nothing changes", correct: "A", difficulty: "MEDIUM", category: "Observation" },
  { question: "If you have only one match and enter a cold room with a lamp, an oil heater, and a candle, what should you light first?", answerA: "The match", answerB: "The lamp", correct: "A", difficulty: "EASY", category: "Observation" },
  { question: "A photograph shows a man; you're told 'brothers and sisters I have none, but this man's father is my father's son.' Who does the man see?", answerA: "His own son", answerB: "His father", correct: "A", difficulty: "HARD", category: "Observation" },

  // ---- Word ----
  { question: "Which word means the opposite of 'ancient'?", answerA: "Modern", answerB: "Old", correct: "A", difficulty: "EASY", category: "Word" },
  { question: "Rearrange 'LISTEN' to form another common word.", answerA: "SILENT", answerB: "LINTELS", correct: "A", difficulty: "MEDIUM", category: "Word", explanation: "LISTEN and SILENT are anagrams; LINTELS has an extra letter." },
  { question: "Which is the odd one out: Whisper, Shout, Murmur, Mutter?", answerA: "Shout", answerB: "Murmur", correct: "A", difficulty: "EASY", category: "Word", explanation: "The others all mean speaking quietly." },
  { question: "What 5-letter word becomes shorter when you add two letters to it?", answerA: "SHORT", answerB: "LARGE", correct: "A", difficulty: "MEDIUM", category: "Word", explanation: "SHORT + 'ER' = SHORTER, a play on words." },
  { question: "Which word is spelled the same forwards and backwards: LEVEL or LOVER?", answerA: "LEVEL", answerB: "LOVER", correct: "A", difficulty: "EASY", category: "Word" },
  { question: "Combine 'SUN' and 'FLOWER' — what common word/phrase results?", answerA: "SUNFLOWER", answerB: "FLOWERSUN", correct: "A", difficulty: "EASY", category: "Word" },
  { question: "What do you call a word that reads the same forwards and backwards?", answerA: "Palindrome", answerB: "Anagram", correct: "A", difficulty: "EASY", category: "Word" },
  { question: "Which word doesn't belong: Sprint, Dash, Jog, Wait?", answerA: "Wait", answerB: "Jog", correct: "A", difficulty: "EASY", category: "Word", explanation: "The others all mean running." },
  { question: "'Homophone' pairs sound alike but differ in meaning. Which pair are homophones: 'flower/flour' or 'flower/flowers'?", answerA: "flower/flour", answerB: "flower/flowers", correct: "A", difficulty: "MEDIUM", category: "Word" },
  { question: "Which of these is a valid anagram of 'NIGHT'?", answerA: "THING", answerB: "TIGHTS", correct: "A", difficulty: "EASY", category: "Word", explanation: "THING uses exactly the letters N,I,G,H,T — same as NIGHT. TIGHTS has an extra letter." },

  // ---- Cipher ----
  { question: "Decode the Caesar cipher (shift 3): 'KHOOR'", answerA: "HELLO", answerB: "WORLD", correct: "A", difficulty: "EASY", category: "Cipher", hint: "Shift each letter back by 3." },
  { question: "Decode the Caesar cipher (shift 2): 'YQTNF'", answerA: "WORLD", answerB: "HELLO", correct: "A", difficulty: "MEDIUM", category: "Cipher", hint: "Shift each letter back by 2." },
  { question: "In a simple substitution where A=1, B=2, C=3..., what does '3-1-20' spell?", answerA: "CAT", answerB: "DOG", correct: "A", difficulty: "EASY", category: "Cipher" },
  { question: "Decode the Atbash cipher (A<->Z, B<->Y...): 'SVOOL'", answerA: "HELLO", answerB: "WORLD", correct: "A", difficulty: "HARD", category: "Cipher", hint: "Atbash reflects each letter across the alphabet." },
  { question: "In Morse-style thinking, '... --- ...' is the distress signal. What word is it?", answerA: "SOS", answerB: "HELP", correct: "A", difficulty: "EASY", category: "Cipher" },
  { question: "A reversed word cipher turns 'OLLEH' into what?", answerA: "HELLO", answerB: "WORLD", correct: "A", difficulty: "EASY", category: "Cipher", hint: "Just reverse the letters." },
  { question: "Decode the Caesar cipher (shift 5): 'MJQQT'", answerA: "HELLO", answerB: "MELLO", correct: "A", difficulty: "MEDIUM", category: "Cipher" },
  { question: "Using A=1,B=2,...Z=26, what does '19-16-25' spell?", answerA: "SPY", answerB: "FLY", correct: "A", difficulty: "MEDIUM", category: "Cipher" },
  { question: "Decode the Atbash cipher: 'Gsviv' (capital G maps like lowercase pattern, ignore case)", answerA: "There", answerB: "Where", correct: "A", difficulty: "HARD", category: "Cipher" },

  // ---- Deduction ----
  { question: "Amy is taller than Ben. Ben is taller than Cara. Who is shortest?", answerA: "Cara", answerB: "Amy", correct: "A", difficulty: "EASY", category: "Deduction" },
  { question: "Four friends sit in a circle. Dana is opposite Eli. Fay is to Dana's left. Where is Fay relative to Eli?", answerA: "To Eli's right", answerB: "Opposite Eli", correct: "A", difficulty: "MEDIUM", category: "Deduction" },
  { question: "Only one of these is true: 'The key is in the drawer' or 'The key is in the box.' It's not in the drawer. Where is it?", answerA: "In the box", answerB: "Nowhere", correct: "A", difficulty: "EASY", category: "Deduction" },
  { question: "Three suspects: only the guilty one lies. Alex says 'Bo is guilty.' Bo says 'I am not guilty.' Cody says 'Alex is telling the truth.' Who is guilty?", answerA: "Bo", answerB: "Alex", correct: "A", difficulty: "HARD", category: "Deduction", explanation: "If Bo is guilty, Bo lies (consistent with 'I am not guilty' being false), and Alex/Cody's truths hold." },
  { question: "Five houses, each a different color, in a row. The red house is immediately left of the blue house. The green house is at one end. Could the green house be red?", answerA: "No, they're different colors by definition", answerB: "Yes", correct: "A", difficulty: "EASY", category: "Deduction" },
  { question: "A is older than B. C is younger than B. Is A definitely older than C?", answerA: "Yes", answerB: "No", correct: "A", difficulty: "EASY", category: "Deduction", explanation: "Transitivity of 'older than'." },
  { question: "In a race, Sam finished before Lee but after Kim. Who finished first?", answerA: "Kim", answerB: "Sam", correct: "A", difficulty: "MEDIUM", category: "Deduction" },
  { question: "Of three brothers, exactly one always tells the truth and the other two always lie. Two brothers say 'It's raining' and one says 'It's not raining.' Is it raining?", answerA: "No", answerB: "Yes", correct: "A", difficulty: "HARD", category: "Deduction", explanation: "Only one brother is truthful. Since two brothers agree it's raining, at least one of them must be a liar — so the pair saying 'raining' can't both be honest, meaning the lone dissenter is the truth-teller." },
  { question: "If all the coins in a bag are gold except two, all are silver except two, and all are bronze except two, how many coins are there?", answerA: "3", answerB: "6", correct: "A", difficulty: "HARD", category: "Deduction", explanation: "One gold, one silver, one bronze — each condition leaves exactly two of the other types." },

  // ---- Mathematical reasoning ----
  { question: "What is 15% of 200?", answerA: "30", answerB: "20", correct: "A", difficulty: "EASY", category: "Mathematical reasoning" },
  { question: "If a train travels 60 miles in 1.5 hours, what is its average speed?", answerA: "40 mph", answerB: "45 mph", correct: "A", difficulty: "EASY", category: "Mathematical reasoning" },
  { question: "A shirt costs $40 after a 20% discount. What was the original price?", answerA: "$48", answerB: "$50", correct: "B", difficulty: "MEDIUM", category: "Mathematical reasoning", explanation: "40 / 0.8 = 50." },
  { question: "You flip a fair coin twice. What is the probability of getting exactly one head?", answerA: "1/2", answerB: "1/4", correct: "A", difficulty: "MEDIUM", category: "Mathematical reasoning", explanation: "HT and TH out of 4 outcomes = 2/4 = 1/2." },
  { question: "Three consecutive integers sum to 60. What is the largest?", answerA: "20", answerB: "21", correct: "B", difficulty: "MEDIUM", category: "Mathematical reasoning", explanation: "19+20+21=60." },
  { question: "A rectangle has a perimeter of 30 and a length of 9. What is its width?", answerA: "6", answerB: "7", correct: "A", difficulty: "EASY", category: "Mathematical reasoning", explanation: "Perimeter=2(l+w), 30=2(9+w), w=6." },
  { question: "If x + 5 = 2x - 3, what is x?", answerA: "8", answerB: "7", correct: "A", difficulty: "EASY", category: "Mathematical reasoning" },
  { question: "A tank fills in 4 hours with one pipe and empties in 6 hours with a drain. If both are open, how long to fill?", answerA: "10 hours", answerB: "12 hours", correct: "B", difficulty: "HARD", category: "Mathematical reasoning", explanation: "Net rate = 1/4 - 1/6 = 1/12, so 12 hours." },
  { question: "What is the sum of the first 10 positive integers?", answerA: "55", answerB: "50", correct: "A", difficulty: "EASY", category: "Mathematical reasoning", explanation: "n(n+1)/2 = 10*11/2 = 55." },
  { question: "A car depreciates 10% per year. After 2 years, what fraction of its value remains (approx)?", answerA: "81%", answerB: "80%", correct: "A", difficulty: "HARD", category: "Mathematical reasoning", explanation: "0.9 * 0.9 = 0.81." },
  { question: "If 3 workers finish a job in 12 days, how long would 6 workers take (same rate)?", answerA: "6 days", answerB: "9 days", correct: "A", difficulty: "MEDIUM", category: "Mathematical reasoning", explanation: "Inversely proportional: 3*12/6=6." },
  { question: "What is the next prime number after 13?", answerA: "15", answerB: "17", correct: "B", difficulty: "MEDIUM", category: "Mathematical reasoning" },

  // ---- Mystery ----
  { question: "A man is found dead in a locked room with a puddle of water and broken glass. What likely happened?", answerA: "An ice sculpture melted, no forced entry needed", answerB: "Someone escaped through the wall", correct: "A", difficulty: "MEDIUM", category: "Mystery" },
  { question: "A woman is found dead in a phone booth still holding the receiver, with no injuries. The detective suspects fright. What clue supports natural causes over foul play?", answerA: "No signs of struggle or forced entry", answerB: "The phone was ringing", correct: "A", difficulty: "MEDIUM", category: "Mystery" },
  { question: "A store's silent alarm never triggered during a robbery, yet nothing was taken. What's the likely explanation?", answerA: "It was an inside test, not a real robbery", answerB: "The alarm was broken", correct: "A", difficulty: "HARD", category: "Mystery" },
  { question: "Detective finds a suspect's alibi is a movie ticket stub timestamped during the crime, but the theater was closed that day for renovations. What does this suggest?", answerA: "The alibi is fabricated", answerB: "The ticket is valid", correct: "A", difficulty: "MEDIUM", category: "Mystery" },
  { question: "A victim's watch stopped at 3:15, and the suspect claims innocence because they left at 3:00. What single detail could break the alibi?", answerA: "If the watch was manually set to mislead investigators", answerB: "Nothing, the alibi is solid", correct: "A", difficulty: "HARD", category: "Mystery" },
  { question: "A campsite is undisturbed except a snapped twig and fresh mud near the tent, though it hasn't rained in a week. What does the mud suggest?", answerA: "Someone tracked it in from elsewhere (a nearby stream)", answerB: "It rained locally overnight", correct: "A", difficulty: "MEDIUM", category: "Mystery" },
  { question: "A locked-room theft occurred, but the window was found unlocked from the inside. What does this tell the detective?", answerA: "The thief left through the window and relocked nothing, exiting last", answerB: "The thief teleported", correct: "A", difficulty: "EASY", category: "Mystery" },
  { question: "A suspect's shoes are clean despite claiming to have walked through mud to reach the scene. What does this imply?", answerA: "The suspect is lying about their path", answerB: "The mud dried instantly", correct: "A", difficulty: "EASY", category: "Mystery" },
  { question: "A guest checks out of a hotel at the time the front desk clock reads 9:00, but security footage timestamped 8:45 shows them leaving. What's the simplest explanation?", answerA: "The front desk clock is running fast", answerB: "The guest checked out twice", correct: "A", difficulty: "MEDIUM", category: "Mystery" },
  { question: "What comes next?\n1, 3, 6, 10, 15, ?", answerA: "18", answerB: "21", correct: "B", difficulty: "MEDIUM", category: "Pattern", explanation: "Triangular numbers: add one more each time (+6)." },
  { question: "If a plane crashes exactly on the border of two countries, where are the survivors buried?", answerA: "Survivors aren't buried", answerB: "Split evenly between both countries", correct: "A", difficulty: "EASY", category: "Logic" },
  { question: "A farmer needs to cross a river with a fox, a chicken, and a bag of grain, taking only one at a time, never leaving fox+chicken or chicken+grain alone together. What must he take first?", answerA: "The chicken", answerB: "The fox", correct: "A", difficulty: "HARD", category: "Deduction", explanation: "Taking the chicken first is the only choice that avoids leaving an unsafe pair behind." },
  { question: "What is 7 squared minus 4 squared?", answerA: "33", answerB: "35", correct: "A", difficulty: "EASY", category: "Mathematical reasoning", explanation: "49 - 16 = 33." },
];
